using System.Collections;
using System.Collections.Generic;
using UnityEngine;
/*
// ADD TIMER FOR HOW LONG OBJECTS LIVE  AND CHANGE SO THAT WE USE DAYS AND MONTHS


// ADD A SYSTEM FOR NEW LEVELS
// ADD ARTIFACTS
// ADD EVENTS FOR NEW DAYS
// ADD GLOBAL STATE MACHINE - added basics
// ADD A MANAGER FOR GLOBAL RESOURCES - Kind of started
// DIALOG BOXES
*/
