// Auto-generated by AutoCardEnumGenerator
public enum CardNames
{
    CollectiveDefence,
    DefensiveOutpost,
    DivineRevitalization,
    GetFollowers,
    GrowForest,
    HeavyArtillery,
    Hut,
    Incence,
    LightArtillery,
    LongTermDefence,
    LookoutOutpost,
    Mine,
    MineLayer,
    Negotiations,
    OffensiveOutpost,
    RaiseMountain,
    Recycle,
    ScapeGoating,
    Sniper,
    TerrorizeTheWeak,
}
